---
plex:
   server: localhost
   machineIdentifier: <MACHINEIDENTIFIER> 
hue:
   hub_ip: 192.168.1.12
   starttransitiontime: 60
   pausedtransitiontime: 15
   stoptransitiontime: 100
   lights: ["Bedroom-lamp", "Bedroom-ceiling"]
